# Generated by Django 5.1.7 on 2025-05-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_forumcategory_forumpost_forumcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('password', models.CharField(max_length=128)),
                ('otp', models.CharField(max_length=6)),
                ('otp_created_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='forumcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='likes',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ForumCategory',
        ),
        migrations.DeleteModel(
            name='ForumComment',
        ),
        migrations.DeleteModel(
            name='ForumPost',
        ),
    ]
