# Generated by Django 5.1.7 on 2025-05-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_bio_customuser_certifications_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='farm_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='farming_experience',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='farming_methods',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='irrigation_types',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='land_area',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='land_unit',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='main_crops',
        ),
    ]
