# Generated by Django 5.1.7 on 2025-05-16 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_customuser_password_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.CharField(max_length=20, unique=True)),
                ('scheme_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(default='Bank of Baroda', max_length=100)),
                ('loan_type', models.CharField(max_length=100)),
                ('interest_rate_min', models.FloatField()),
                ('interest_rate_max', models.FloatField()),
                ('interest_rate_note', models.TextField(blank=True, null=True)),
                ('repayment_term_months', models.IntegerField()),
                ('repayment_category', models.CharField(max_length=50)),
                ('eligibility', models.JSONField()),
                ('description', models.TextField()),
                ('key_benefits', models.JSONField()),
                ('loan_limit_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_limit_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('loan_limit_note', models.TextField(blank=True, null=True)),
                ('collateral_required', models.TextField()),
                ('loan_purpose', models.JSONField()),
                ('processing_fee_note', models.TextField(blank=True, null=True)),
                ('subsidy_available', models.BooleanField(default=False)),
                ('subsidy_details', models.TextField(blank=True, null=True)),
                ('insurance_linkage', models.JSONField(default=list)),
                ('renewal_period', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
