# Generated by Django 5.1.7 on 2025-05-16 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_loanscheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_size', models.DecimalField(decimal_places=2, help_text='Land size in acres', max_digits=10)),
                ('land_type', models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('both', 'Both Owned and Leased')], max_length=50)),
                ('primary_crops', models.JSONField(default=list, help_text='List of primary crops grown')),
                ('crop_seasons', models.JSONField(default=list, help_text='Seasons when crops are grown')),
                ('annual_income', models.DecimalField(decimal_places=2, help_text='Annual income in INR', max_digits=12)),
                ('existing_loans', models.JSONField(blank=True, default=list, help_text='Details of existing loans')),
                ('has_land_documents', models.BooleanField(default=False)),
                ('has_income_proof', models.BooleanField(default=False)),
                ('has_identity_proof', models.BooleanField(default=False)),
                ('irrigation_source', models.CharField(blank=True, max_length=100, null=True)),
                ('farming_experience_years', models.IntegerField(default=0)),
                ('additional_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(help_text="Score indicating how well the scheme matches the farmer's profile")),
                ('recommended_amount', models.DecimalField(decimal_places=2, help_text='Recommended loan amount', max_digits=12)),
                ('recommendation_reason', models.TextField(help_text='Explanation of why this loan is recommended')),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_recommendations', to=settings.AUTH_USER_MODEL)),
                ('loan_scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.loanscheme')),
            ],
            options={
                'ordering': ['-match_score'],
            },
        ),
    ]
