# Generated by Django 5.1.7 on 2025-05-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_farmerprofile_loanrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanrecommendation',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='loanrecommendation',
            name='loan_scheme',
        ),
        migrations.AddField(
            model_name='customuser',
            name='crops_grown',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='equipment_owned',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='farm_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='farm_size_unit',
            field=models.CharField(blank=True, default='acres', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='farming_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='irrigation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='soil_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='FarmerProfile',
        ),
        migrations.DeleteModel(
            name='LoanRecommendation',
        ),
    ]
