# Generated by Django 5.1.7 on 2025-05-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_loanscheme_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_group', models.CharField(max_length=200)),
                ('eligibility', models.TextField()),
                ('benefits', models.TextField()),
                ('how_to_apply', models.TextField()),
                ('required_documents', models.TextField()),
                ('contact', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('language_support', models.TextField(blank=True, null=True)),
                ('faq', models.TextField(blank=True, null=True)),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['scheme_id'],
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='crops_grown',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='equipment_owned',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='farm_size',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='farm_size_unit',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='farming_experience',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='irrigation_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='loanscheme',
            name='id',
        ),
    ]
