# Generated by Django 5.1.7 on 2025-05-18 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_governmentscheme_remove_customuser_crops_grown_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GovernmentScheme',
        ),
    ]
