# Generated by Django 5.1.7 on 2025-05-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_government_scheme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('scheme_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('target_group', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('CENTRAL', 'Central Government'), ('KA', 'Karnataka'), ('MH', 'Maharashtra')], default='CENTRAL', max_length=20)),
                ('language_support', models.JSONField()),
                ('eligibility', models.JSONField()),
                ('benefits', models.JSONField()),
                ('how_to_apply', models.JSONField()),
                ('required_documents', models.JSONField()),
                ('contact', models.JSONField()),
                ('faq', models.JSONField()),
            ],
        ),
    ]
