# Generated by Django 5.1.7 on 2025-05-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_scheme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Scheme',
        ),
        migrations.AddField(
            model_name='loanscheme',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='loanscheme',
            name='contact_info',
            field=models.TextField(blank=True, help_text='Additional contact information', null=True),
        ),
        migrations.AddField(
            model_name='loanscheme',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loanscheme',
            name='contact_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
