# Generated by Django 5.1.7 on 2025-05-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_delete_scheme_loanscheme_contact_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentScheme',
            fields=[
                ('scheme_id', models.CharField(help_text='Unique identifier for the scheme', max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the government scheme', max_length=255)),
                ('type', models.CharField(help_text='Type/category of the scheme', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of the scheme')),
                ('target_group', models.CharField(help_text='Target beneficiaries of the scheme', max_length=255)),
                ('status', models.CharField(help_text='Current status of the scheme (Active/Inactive/etc)', max_length=50)),
                ('state', models.CharField(choices=[('CENTRAL', 'Central Government'), ('KA', 'Karnataka'), ('MH', 'Maharashtra')], default='CENTRAL', help_text='State or central government scheme', max_length=20)),
                ('language_support', models.JSONField(help_text='Supported languages and their content')),
                ('eligibility', models.JSONField(help_text='Eligibility criteria in structured format')),
                ('benefits', models.JSONField(help_text='Benefits provided by the scheme')),
                ('how_to_apply', models.JSONField(help_text='Application process and steps')),
                ('required_documents', models.JSONField(help_text='List of required documents')),
                ('contact', models.JSONField(help_text='Contact information and support details')),
                ('faq', models.JSONField(help_text='Frequently asked questions and answers')),
            ],
        ),
    ]
