# Generated by Django 5.1.7 on 2025-05-19 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_governmentscheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentscheme',
            name='benefits',
            field=models.JSONField(blank=True, default=list, help_text='Benefits provided by the scheme', null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='contact',
            field=models.JSONField(blank=True, default=dict, help_text='Contact information and support details', null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='eligibility',
            field=models.JSONField(blank=True, default=dict, help_text='Eligibility criteria in structured format', null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='faq',
            field=models.JSONField(blank=True, default=list, help_text='Frequently asked questions and answers', null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='how_to_apply',
            field=models.JSONField(blank=True, default=dict, help_text='Application process and steps', null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='language_support',
            field=models.JSONField(blank=True, default=list, help_text='Supported languages and their content', null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='required_documents',
            field=models.JSONField(blank=True, default=list, help_text='List of required documents', null=True),
        ),
        migrations.AlterField(
            model_name='governmentscheme',
            name='state',
            field=models.CharField(choices=[('CENTRAL', 'Central Government'), ('KA', 'Karnataka'), ('MH', 'Maharashtra'), ('AP', 'Andhra Pradesh'), ('TN', 'Tamil Nadu'), ('UP', 'Uttar Pradesh'), ('GJ', 'Gujarat'), ('WB', 'West Bengal'), ('RJ', 'Rajasthan'), ('MP', 'Madhya Pradesh'), ('ALL', 'All States')], default='CENTRAL', help_text='State or central government scheme', max_length=20),
        ),
    ]
