# Generated by Django 5.1.7 on 2025-05-20 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_governmentscheme_benefits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentscheme',
            name='state',
            field=models.CharField(choices=[('CENTRAL', 'Central Government'), ('KA', 'Karnataka'), ('MH', 'Maharashtra')], default='CENTRAL', help_text='State or central government scheme', max_length=20),
        ),
        migrations.CreateModel(
            name='FarmResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Farm Resource',
                'verbose_name_plural': 'Farm Resources',
            },
        ),
    ]
