# Generated by Django 5.1.7 on 2025-05-22 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_governmentscheme_state_farmresource'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(help_text='Nitrogen content in soil (kg/ha)')),
                ('phosphorus', models.FloatField(help_text='Phosphorus content in soil (kg/ha)')),
                ('potassium', models.FloatField(help_text='Potassium content in soil (kg/ha)')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity percentage')),
                ('soil_moisture', models.FloatField(help_text='Soil moisture percentage')),
                ('soil_type', models.CharField(help_text='Type of soil', max_length=50)),
                ('crop_type', models.CharField(help_text='Type of crop', max_length=50)),
                ('recommended_fertilizer', models.CharField(max_length=100)),
                ('recommendation_reason', models.TextField()),
                ('application_rate', models.CharField(max_length=100)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fertilizer_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
