# Generated by Django 5.1.7 on 2025-06-08 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_fertilizerrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FertilizerRecommendation',
        ),
    ]
