# Generated by Django 5.0.4 on 2025-06-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_delete_fertilizerrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
