# Generated by Django 5.1.7 on 2025-05-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_district_governmentscheme_loanoption_organicpractice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmdetail',
            name='nitrogen_value',
            field=models.FloatField(blank=True, help_text='Nitrogen content in kg/ha', null=True),
        ),
        migrations.AddField(
            model_name='farmdetail',
            name='ph_value',
            field=models.FloatField(blank=True, help_text='Soil pH value', null=True),
        ),
        migrations.AddField(
            model_name='farmdetail',
            name='phosphorus_value',
            field=models.FloatField(blank=True, help_text='Phosphorus content in kg/ha', null=True),
        ),
        migrations.AddField(
            model_name='farmdetail',
            name='potassium_value',
            field=models.FloatField(blank=True, help_text='Potassium content in kg/ha', null=True),
        ),
    ]
