# Generated by Django 5.1.7 on 2025-05-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_farmdetail_nitrogen_value_farmdetail_ph_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmingexperience',
            name='years_experience',
            field=models.CharField(default='', max_length=50),
        ),
    ]
