# Generated by Django 5.1.7 on 2025-05-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_farmingexperience_years_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentscheme',
            name='detailed_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='how_to_apply',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='governmentscheme',
            name='official_website',
            field=models.CharField(default='', max_length=200),
        ),
    ]
