# Generated by Django 5.1.7 on 2025-06-03 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_governmentscheme_detailed_description_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            # Forward SQL - Remove the column if it exists
            """
            PRAGMA foreign_keys=off;
            
            CREATE TABLE IF NOT EXISTS new_main_app_loanoption (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(100) NOT NULL,
                provider VARCHAR(100) NOT NULL,
                loan_type VARCHAR(50) NOT NULL,
                interest_rate VARCHAR(50) NOT NULL,
                max_amount DECIMAL NOT NULL,
                tenure VARCHAR(50) NOT NULL,
                eligibility TEXT NOT NULL,
                documents_required TEXT NOT NULL,
                processing_time VARCHAR(50) NOT NULL,
                special_features TEXT NOT NULL
            );
            
            INSERT INTO new_main_app_loanoption (
                id, name, provider, loan_type, interest_rate, max_amount, 
                tenure, eligibility, documents_required, processing_time, special_features
            )
            SELECT 
                id, name, provider, loan_type, interest_rate, max_amount, 
                tenure, eligibility, documents_required, processing_time, special_features
            FROM main_app_loanoption;
            
            DROP TABLE main_app_loanoption;
            ALTER TABLE new_main_app_loanoption RENAME TO main_app_loanoption;
            
            PRAGMA foreign_keys=on;
            """,
            # Reverse SQL - Do nothing as we can't restore the column
            "SELECT 1;"
        )
    ]
