# Generated by Django 5.1.7 on 2025-06-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20250603_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropeconomics',
            name='drought_resistance',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cropeconomics',
            name='growth_period',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cropeconomics',
            name='market_demand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cropeconomics',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cropeconomics',
            name='ph_range',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='cropeconomics',
            name='rainfall_range_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropeconomics',
            name='rainfall_range_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropeconomics',
            name='temperature_range_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropeconomics',
            name='temperature_range_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropeconomics',
            name='water_requirement',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
