# Generated by Django 5.1.7 on 2025-06-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_cropeconomics_drought_resistance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropeconomics',
            name='season',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
