# Generated by Django 5.1.7 on 2025-06-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_add_fertilizer_product_data'),
    ]

    operations = [
    ]
