# Generated by Django 5.1.7 on 2025-06-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_add_fertilizer_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='basal_application',
            field=models.TextField(blank=True, help_text='Instructions for basal/pre-planting application'),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='foliar_spray',
            field=models.TextField(blank=True, help_text='Foliar spray recommendations if applicable'),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='micronutrients',
            field=models.TextField(blank=True, help_text='Recommended micronutrients if needed'),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='primary_fertilizers',
            field=models.TextField(blank=True, help_text='List of specific fertilizer products recommended as primary source'),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='secondary_fertilizers',
            field=models.TextField(blank=True, help_text='List of specific fertilizer products recommended as secondary source'),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='soil_amendments',
            field=models.TextField(blank=True, help_text='Recommended soil amendments based on soil type'),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='top_dressing',
            field=models.TextField(blank=True, help_text='Instructions for top dressing/side dressing during growth'),
        ),
    ]
