# Generated by Django 5.1.7 on 2025-06-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_populate_fertilizer_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizerrecommendation',
            name='primary_fertilizers',
            field=models.TextField(blank=True, help_text='List of primary fertilizer products recommended'),
        ),
        migrations.AlterField(
            model_name='fertilizerrecommendation',
            name='secondary_fertilizers',
            field=models.TextField(blank=True, help_text='List of secondary fertilizer products recommended'),
        ),
    ]
