# Generated by Django 5.1.7 on 2025-06-06 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_populate_fertilizer_data'),
        ('main_app', '0013_alter_fertilizerrecommendation_primary_fertilizers_and_more'),
    ]

    operations = [
    ]
