# Generated by Django 5.1.7 on 2025-06-06 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_merge_20250606_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmerinterest',
            name='new_varieties_interest',
        ),
        migrations.RemoveField(
            model_name='farmingexperience',
            name='typical_yield',
        ),
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='basal_application',
        ),
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='foliar_spray',
        ),
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='micronutrients',
        ),
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='primary_fertilizers',
        ),
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='secondary_fertilizers',
        ),
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='soil_amendments',
        ),
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='top_dressing',
        ),
    ]
