# Generated by Django 5.1.7 on 2025-06-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_remove_new_varieties_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='recommended_fertilizers',
            field=models.TextField(blank=True, help_text='Recommended fertilizer products based on NPK values'),
        ),
    ]
