# Generated by Django 5.1.7 on 2025-06-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_fertilizerrecommendation_recommended_fertilizers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizerrecommendation',
            name='recommended_fertilizers',
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='dap_kg_per_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='mop_kg_per_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='npk_complex_kg_per_ha',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='fertilizerrecommendation',
            name='urea_kg_per_ha',
            field=models.FloatField(default=0),
        ),
    ]
