# Generated by Django 5.1.7 on 2025-06-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_add_fertilizer_product_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='technology',
            name='addresses_challenges',
            field=models.CharField(default='', help_text='Comma-separated list of challenges this technology addresses', max_length=255),
        ),
        migrations.AddField(
            model_name='technology',
            name='benefits',
            field=models.TextField(default='', help_text='Key benefits of this technology'),
        ),
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.TextField(default='', help_text='Detailed description of the technology'),
        ),
        migrations.AddField(
            model_name='technology',
            name='difficulty_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='technology',
            name='farm_size_suitability',
            field=models.CharField(choices=[('small', 'Small Farms (< 1 Hectare)'), ('medium', 'Medium Farms (1-5 Hectares)'), ('large', 'Large Farms (> 5 Hectares)'), ('all', 'All Farm Sizes')], default='all', max_length=10),
        ),
        migrations.AddField(
            model_name='technology',
            name='financing_options',
            field=models.TextField(blank=True, help_text='Information about financing options'),
        ),
        migrations.AddField(
            model_name='technology',
            name='implementation_steps',
            field=models.TextField(blank=True, help_text='Step-by-step implementation guide'),
        ),
        migrations.AddField(
            model_name='technology',
            name='implementation_time',
            field=models.CharField(default='Varies', max_length=100),
        ),
        migrations.AddField(
            model_name='technology',
            name='is_portable',
            field=models.BooleanField(default=False, help_text='Whether the technology can be easily relocated'),
        ),
        migrations.AddField(
            model_name='technology',
            name='learn_more_url',
            field=models.URLField(blank=True, help_text='URL for more information'),
        ),
        migrations.AddField(
            model_name='technology',
            name='lifespan_years',
            field=models.IntegerField(default=0, help_text='Expected lifespan in years'),
        ),
        migrations.AddField(
            model_name='technology',
            name='limitations',
            field=models.TextField(default='', help_text='Limitations or drawbacks of this technology'),
        ),
        migrations.AddField(
            model_name='technology',
            name='maintenance_requirements',
            field=models.TextField(blank=True, help_text='Ongoing maintenance needs'),
        ),
        migrations.AddField(
            model_name='technology',
            name='organic_compatible',
            field=models.BooleanField(default=True, help_text='Whether suitable for organic farming'),
        ),
        migrations.AddField(
            model_name='technology',
            name='seasonal_suitability',
            field=models.CharField(choices=[('kharif', 'Kharif (Monsoon)'), ('rabi', 'Rabi (Winter)'), ('zaid', 'Zaid (Summer)'), ('year_round', 'Year Round')], default='year_round', max_length=20),
        ),
        migrations.AddField(
            model_name='technology',
            name='simple_description',
            field=models.TextField(blank=True, help_text='Simplified explanation for basic education levels'),
        ),
        migrations.AddField(
            model_name='technology',
            name='subsidy_available',
            field=models.BooleanField(default=False, help_text='Whether government subsidies are available'),
        ),
        migrations.AddField(
            model_name='technology',
            name='subsidy_details',
            field=models.TextField(blank=True, help_text='Details about available subsidies'),
        ),
        migrations.AddField(
            model_name='technology',
            name='success_stories',
            field=models.TextField(blank=True, help_text='Examples of successful implementation'),
        ),
        migrations.AddField(
            model_name='technology',
            name='technical_details',
            field=models.TextField(blank=True, help_text='Advanced technical details for higher education levels'),
        ),
    ]
