# Generated by Django 5.1.7 on 2025-06-10 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_technology_addresses_challenges_technology_benefits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='addresses_challenges',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='benefits',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='description',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='difficulty_level',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='farm_size_suitability',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='financing_options',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='implementation_steps',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='implementation_time',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='is_portable',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='learn_more_url',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='lifespan_years',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='limitations',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='maintenance_requirements',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='organic_compatible',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='seasonal_suitability',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='simple_description',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='subsidy_available',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='subsidy_details',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='success_stories',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='technical_details',
        ),
        migrations.AddField(
            model_name='loanoption',
            name='benefits',
            field=models.TextField(blank=True, help_text='Key benefits of the loan', null=True),
        ),
    ]
