# Generated by Django 5.1.7 on 2025-06-10 14:55

from django.db import migrations, models
import django.db.models.deletion


def forward_func(apps, schema_editor):
    # Get the FarmerProfile model
    FarmerProfile = apps.get_model('main_app', 'FarmerProfile')
    CustomUser = apps.get_model('myapp', 'CustomUser')
    
    # Get all existing user IDs
    valid_user_ids = set(CustomUser.objects.values_list('id', flat=True))
    
    # Set invalid user references to NULL
    for profile in FarmerProfile.objects.all():
        if profile.user_id and profile.user_id not in valid_user_ids:
            profile.user = None
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_farmerprofile_user'),
    ]

    operations = [
        # First set invalid foreign keys to NULL
        migrations.RunPython(forward_func, migrations.RunPython.noop),
        
        # Then alter the field to allow NULL values
        migrations.AlterField(
            model_name='farmerprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to='myapp.customuser'),
        ),
    ]
